// Code generated by goctl. DO NOT EDIT.
// Source: curriculacenter.proto

package curriculacenter

import (
	"context"

	"github.com/MuxiKeStack/muxiK-StackBackend2.0/app/curricula/cmd/rpc/pb/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddCurriculaRequest  = pb.AddCurriculaRequest
	AddCurriculaResponse = pb.AddCurriculaResponse

	Curriculacenter interface {
		AddCurricula(ctx context.Context, in *AddCurriculaRequest, opts ...grpc.CallOption) (*AddCurriculaResponse, error)
	}

	defaultCurriculacenter struct {
		cli zrpc.Client
	}
)

func NewCurriculacenter(cli zrpc.Client) Curriculacenter {
	return &defaultCurriculacenter{
		cli: cli,
	}
}

func (m *defaultCurriculacenter) AddCurricula(ctx context.Context, in *AddCurriculaRequest, opts ...grpc.CallOption) (*AddCurriculaResponse, error) {
	client := pb.NewCurriculacenterClient(m.cli.Conn())
	return client.AddCurricula(ctx, in, opts...)
}
