// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	message "github.com/MuxiKeStack/muxiK-StackBackend2.0/app/message/cmd/api/internal/handler/message"
	"github.com/MuxiKeStack/muxiK-StackBackend2.0/app/message/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/connect",
				Handler: message.SocketConnectHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/normal",
				Handler: message.SendNormalMessageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/official",
				Handler: message.SendOfficialMessageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/official",
				Handler: message.GetOfficialMessageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/normal",
				Handler: message.GetNormalMessageHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/message"),
	)
}
