// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"github.com/MuxiKeStack/muxiK-StackBackend2.0/app/qiniu/cmd/api/internal/svc"
	"net/http"
	qiniu "github.com/MuxiKeStack/muxiK-StackBackend2.0/app/qiniu/cmd/api/internal/handler/qiniu"
	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/token",
				Handler: qiniu.Qiniu_tokenHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/qiniu"),
	)
}
