// Code generated by goctl. DO NOT EDIT.
// Source: user_center.proto

package usercenter

import (
	"context"

	"github.com/MuxiKeStack/muxiK-StackBackend2.0/app/user/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GenerateTokenRequest  = pb.GenerateTokenRequest
	GenerateTokenResponse = pb.GenerateTokenResponse
	LoginRequest          = pb.LoginRequest
	LoginResponse         = pb.LoginResponse

	Usercenter interface {
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	}

	defaultUsercenter struct {
		cli zrpc.Client
	}
)

func NewUsercenter(cli zrpc.Client) Usercenter {
	return &defaultUsercenter{
		cli: cli,
	}
}

func (m *defaultUsercenter) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := pb.NewUsercenterClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}
