// Code generated by goctl. DO NOT EDIT.
// Source: curriculacenter.proto

package server

import (
	"context"

	"github.com/MuxiKeStack/muxiK-StackBackend2.0/app/curricula/cmd/rpc/internal/logic"
	"github.com/MuxiKeStack/muxiK-StackBackend2.0/app/curricula/cmd/rpc/internal/svc"
	"github.com/MuxiKeStack/muxiK-StackBackend2.0/app/curricula/cmd/rpc/pb/pb"
)

type CurriculacenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCurriculacenterServer
}

func NewCurriculacenterServer(svcCtx *svc.ServiceContext) *CurriculacenterServer {
	return &CurriculacenterServer{
		svcCtx: svcCtx,
	}
}

func (s *CurriculacenterServer) AddCurricula(ctx context.Context, in *pb.AddCurriculaRequest) (*pb.AddCurriculaResponse, error) {
	l := logic.NewAddCurriculaLogic(ctx, s.svcCtx)
	return l.AddCurricula(in)
}
