// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/MuxiKeStack/muxiK-StackBackend2.0/app/curricula/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: addCurriculaHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/delete",
				Handler: deleteCurriculaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: updateCurriculaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/search",
				Handler: searchCurriculaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/detail",
				Handler: curriculumDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/check_type",
				Handler: checkCharacteristicsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/random_curricula",
				Handler: randomCurriculaHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/curricula"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthorizeHandler.Handle},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/collect",
					Handler: collectCurriculumHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/deleteCollection",
					Handler: deleteCollectionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getAllCollection",
					Handler: getAllCollectionHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v1/user"),
	)
}
