// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	collectionsFieldNames          = builder.RawFieldNames(&Collections{})
	collectionsRows                = strings.Join(collectionsFieldNames, ",")
	collectionsRowsExpectAutoSet   = strings.Join(stringx.Remove(collectionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	collectionsRowsWithPlaceHolder = strings.Join(stringx.Remove(collectionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	collectionsModel interface {
		Insert(ctx context.Context, data *Collections) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Collections, error)
		Update(ctx context.Context, data *Collections) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCollectionsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Collections struct {
		Id      int64  `db:"id"`
		Sid     string `db:"sid"`
		CDataId int64  `db:"c_data_id"`
	}
)

func newCollectionsModel(conn sqlx.SqlConn) *defaultCollectionsModel {
	return &defaultCollectionsModel{
		conn:  conn,
		table: "`collections`",
	}
}

func (m *defaultCollectionsModel) withSession(session sqlx.Session) *defaultCollectionsModel {
	return &defaultCollectionsModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`collections`",
	}
}

func (m *defaultCollectionsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCollectionsModel) FindOne(ctx context.Context, id int64) (*Collections, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", collectionsRows, m.table)
	var resp Collections
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCollectionsModel) Insert(ctx context.Context, data *Collections) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, collectionsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Sid, data.CDataId)
	return ret, err
}

func (m *defaultCollectionsModel) Update(ctx context.Context, data *Collections) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, collectionsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Sid, data.CDataId, data.Id)
	return err
}

func (m *defaultCollectionsModel) tableName() string {
	return m.table
}
