// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	comment "github.com/MuxiKeStack/muxiK-StackBackend2.0/app/evaluation1/cmd/api/internal/handler/comment"
	reply "github.com/MuxiKeStack/muxiK-StackBackend2.0/app/evaluation1/cmd/api/internal/handler/reply"
	"github.com/MuxiKeStack/muxiK-StackBackend2.0/app/evaluation1/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/comment",
				Handler: comment.CommentEvaluationHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/comment",
				Handler: comment.DeleteCommentHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/evaluation"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/comment/reply",
				Handler: reply.ReplyCommentHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/evaluation"),
	)
}
