// Code generated by goctl. DO NOT EDIT.
// Source: user_center.proto

package server

import (
	"context"

	"github.com/MuxiKeStack/muxiK-StackBackend2.0/app/user/rpc/internal/logic"
	"github.com/MuxiKeStack/muxiK-StackBackend2.0/app/user/rpc/internal/svc"
	"github.com/MuxiKeStack/muxiK-StackBackend2.0/app/user/rpc/pb"
)

type UsercenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUsercenterServer
}

func NewUsercenterServer(svcCtx *svc.ServiceContext) *UsercenterServer {
	return &UsercenterServer{
		svcCtx: svcCtx,
	}
}

func (s *UsercenterServer) Login(ctx context.Context, in *pb.LoginRequest) (*pb.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
