// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	StudentId string `json:"studentId"`
	Password  string `json:"password"`
}

type LoginResponse struct {
	Token string `json:"token"`
	IfNew bool   `json:"ifnew"`
}
