// Code generated by goctl. DO NOT EDIT.
package types

type CommentEvaluationReq struct {
	Authorization      string `header:"Authorization"`
	Content            string `json:"Content"`
	ObjectEvaluationId uint   `json:"ObjectEvaluationId"`
}

type CommentEvaluationRsp struct {
	Flag bool `json:"Flag"`
}

type DeleteCommentReq struct {
	Authorization   string `header:"Authorization"`
	ObjectCommentId uint   `json:"ObjectEvaluationId"`
}

type DeleteCommentRsp struct {
	Flag bool `json:"Flag"`
}

type ReplyCommentReq struct {
	Authorization   string `header:"Authorization"`
	Content         string `json:"Content"`
	ObjectCommentId uint   `json:"ObjectEvaluationId"`
}

type ReplyCommentRsp struct {
	Flag bool `json:"Flag"`
}
