// Code generated by goctl. DO NOT EDIT.
package types

type ConnectReq struct {
	Authorization string `header:"Authorization"`
}

type OfficialMessage struct {
	Title     string `json:"title"`
	Text      string `json:"text"`
	Image     string `json:"image"`
	SendAt    int64  `json:"send_at"`
	ObjectSid string `json:"object_sid,optional"`
}

type SendOfficialMessageReq struct {
	Authorization string          `header:"Authorization"`
	AllUser       bool            `json:"allUser"`
	Msg           OfficialMessage `json:"message"`
}

type SendOfficialMessageRsp struct {
	Flag bool `json:"flag"`
}

type GetOfficialMessageReq struct {
	Authorization string `header:"Authorization"`
}

type GetOfficialMessageRsp struct {
	OfficialMsgs []OfficialMessage `json:"officialMsgs"`
}

type NormalMessage struct {
	Type            string `json:"type"`
	ObjectSid       string `json:"object_sid"`
	SenderId        string `json:"sender_sid"`
	OriginContentId uint   `json:"origin_content_id"`
	Text            string `json:"text"`
	SendAt          int64  `json:"send_at"`
}

type GetNormalMessageReq struct {
	Authorization string `header:"Authorization"`
}

type GetNormalMessageRsp struct {
	NormalMsgs []NormalMessage `json:"normalMsgs"`
}

type SendNormalMessageReq struct {
	Authorization   string `header:"Authorization"`
	Type            string `json:"type"`
	ObjectSid       string `json:"object_sid"`
	OriginContentId uint   `json:"origin_content_id"`
	Text            string `json:"text"`
	SendAt          int64  `json:"send_at"`
}

type SendNormalMessageRsp struct {
	Flag bool `json:"flag"`
}
